=== Full-Thrust/ftDamage/generic/full-thrust-ship-class.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Full Thrust 1E Ship Class",
  "type": "object",
  "required": [
    "classKey",
    "name",
    "thrust",
    "damage",
    "firecons",
    "weapons"
  ],
  "properties": {
    "classKey": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "thrust": {
      "type": "number",
      "minimum": 0
    },
    "damage": {
      "type": "object",
      "required": [
        "total",
        "tracks"
      ],
      "properties": {
        "total": {
          "type": "integer",
          "minimum": 1
        },
        "tracks": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "integer",
              "enum": [
                1
              ]
            }
          }
        }
      },
      "additionalProperties": false
    },
    "firecons": {
      "type": "array",
      "items": {
        "type": "integer",
        "enum": [
          1
        ]
      }
    },
    "weapons": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "type",
          "class",
          "arcs"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "BEAM",
              "NEEDLE",
              "PULSE"
            ]
          },
          "class": {
            "type": "string",
            "enum": [
              "A",
              "B",
              "C"
            ]
          },
          "arcs": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "string",
              "enum": [
                "F",
                "P",
                "S",
                "A"
              ]
            }
          }
        },
        "allOf": [
          {
            "if": {
              "properties": {
                "type": {
                  "const": "NEEDLE"
                }
              }
            },
            "then": {
              "properties": {
                "arcs": {
                  "minItems": 1,
                  "maxItems": 1
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": [
                    "PULSE"
                  ]
                }
              }
            },
            "then": {
              "properties": {
                "arcs": {
                  "type": "array",
                  "minItems": 1,
                  "maxItems": 1,
                  "items": {
                    "type": "string",
                    "const": "F"
                  }
                }
              }
            }
          }
        ],
        "additionalProperties": false
      }
    },
    "fighters": {
      "type": "object",
      "required": [
        "capacity"
      ],
      "properties": {
        "capacity": {
          "type": "integer",
          "minimum": 1
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== Full-Thrust/ftDamage/generic/battleship.shipclass.json
{
  "classKey": "BATTLESHIP",
  "name": "Battleship",
  "thrust": 4,
  "damage": {
    "total": 22,
    "tracks": [
      [1, 1, 1, 1, 1, 1],
      [1, 1, 1, 1, 1, 1],
      [1, 1, 1, 1, 1, 1],
      [1, 1, 1, 1]
    ]
  },
  "firecons": [1, 1, 1],
  "weapons": [
    {
      "type": "BEAM",
      "class": "A",
      "arcs": ["F", "P"]
    },
    {
      "type": "BEAM",
      "class": "A",
      "arcs": ["F", "P"]
    },
    {
      "type": "BEAM",
      "class": "A",
      "arcs": ["F", "S"]
    },
    {
      "type": "BEAM",
      "class": "A",
      "arcs": ["F", "S"]
    },
    {
      "type": "BEAM",
      "class": "B",
      "arcs": ["F", "P", "A"]
    },
    {
      "type": "BEAM",
      "class": "B",
      "arcs": ["F", "P", "A"]
    },
    {
      "type": "BEAM",
      "class": "B",
      "arcs": ["F", "S", "A"]
    },
    {
      "type": "BEAM",
      "class": "B",
      "arcs": ["F", "S", "A"]
    }
  ]
}

=== Full-Thrust/ftDamage/generic/frigate.shipclass.json
{
  "classKey": "FRIGATE",
  "name": "Frigate",
  "thrust": 6,
  "damage": {
    "total": 6,
    "tracks": [
      [
        1,
        1,
        1
      ],
      [
        1,
        1,
        1
      ]
    ]
  },
  "firecons": [
    1
  ],
  "weapons": [
    {
      "type": "BEAM",
      "class": "B",
      "arcs": [
        "F",
        "P",
        "S"
      ]
    },
    {
      "type": "BEAM",
      "class": "C",
      "arcs": [
        "P",
        "S",
        "A"
      ]
    }
  ]
}

=== Full-Thrust/ftDamage/generic/escort_cruiser.shipclass.json
{
  "classKey": "ESCORT_CRUISER",
  "name": "Escort Cruiser",
  "thrust": 6,
  "damage": {
    "total": 14,
    "tracks": [
      [
        1,
        1,
        1,
        1,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1
      ],
      [
        1,
        1,
        1,
        1
      ]
    ]
  },
  "firecons": [
    1,
    1
  ],
  "weapons": [
    {
      "type": "BEAM",
      "class": "A",
      "arcs": [
        "F",
        "P",
        "S"
      ]
    },
    {
      "type": "BEAM",
      "class": "B",
      "arcs": [
        "F",
        "P",
        "A"
      ]
    },
    {
      "type": "BEAM",
      "class": "B",
      "arcs": [
        "F",
        "P",
        "A"
      ]
    },
    {
      "type": "BEAM",
      "class": "B",
      "arcs": [
        "F",
        "S",
        "A"
      ]
    },
    {
      "type": "BEAM",
      "class": "B",
      "arcs": [
        "F",
        "S",
        "A"
      ]
    }
  ]
}

=== Full-Thrust/ftDamage/generic/dreadnought.shipclass.json
{
  "classKey": "DREADNOUGHT",
  "name": "Dreadnought",
  "thrust": 2,
  "damage": {
    "total": 28,
    "tracks": [
      [
        1,
        1,
        1,
        1,
        1,
        1,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1,
        1,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1,
        1,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1,
        1,
        1
      ]
    ]
  },
  "firecons": [
    1,
    1,
    1
  ],
  "weapons": [
    {
      "type": "BEAM",
      "class": "A",
      "arcs": [
        "F"
      ]
    },
    {
      "type": "BEAM",
      "class": "A",
      "arcs": [
        "F"
      ]
    },
    {
      "type": "BEAM",
      "class": "A",
      "arcs": [
        "F"
      ]
    },
    {
      "type": "BEAM",
      "class": "A",
      "arcs": [
        "F",
        "P"
      ]
    },
    {
      "type": "BEAM",
      "class": "A",
      "arcs": [
        "F",
        "P"
      ]
    },
    {
      "type": "BEAM",
      "class": "A",
      "arcs": [
        "F",
        "S"
      ]
    },
    {
      "type": "BEAM",
      "class": "A",
      "arcs": [
        "F",
        "S"
      ]
    },
    {
      "type": "BEAM",
      "class": "B",
      "arcs": [
        "P",
        "S",
        "A"
      ]
    },
    {
      "type": "BEAM",
      "class": "B",
      "arcs": [
        "P",
        "S",
        "A"
      ]
    },
    {
      "type": "BEAM",
      "class": "B",
      "arcs": [
        "P",
        "S",
        "A"
      ]
    },
    {
      "type": "BEAM",
      "class": "B",
      "arcs": [
        "P",
        "S",
        "A"
      ]
    }
  ],
  "fighters": {
    "capacity": 6
  }
}

=== Full-Thrust/ftDamage/generic/lancer_corvette.shipclass.json
{
  "classKey": "LANCER_CORVETTE",
  "name": "Lancer / Corvette",
  "thrust": 8,
  "damage": {
    "total": 4,
    "tracks": [
      [
        1,
        1
      ],
      [
        1,
        1
      ]
    ]
  },
  "firecons": [
    1
  ],
  "weapons": [
    {
      "type": "BEAM",
      "class": "B",
      "arcs": [
        "F",
        "P",
        "S",
        "A"
      ]
    }
  ]
}

=== Full-Thrust/ftDamage/generic/carrier.shipclass.json
{
  "classKey": "CARRIER",
  "name": "Carrier",
  "thrust": 2,
  "damage": {
    "total": 24,
    "tracks": [
      [
        1,
        1,
        1,
        1,
        1,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1,
        1
      ]
    ]
  },
  "firecons": [
    1,
    1,
    1
  ],
  "weapons": [
    {
      "type": "BEAM",
      "class": "B",
      "arcs": [
        "F",
        "P",
        "S"
      ]
    },
    {
      "type": "BEAM",
      "class": "B",
      "arcs": [
        "F",
        "P",
        "S"
      ]
    },
    {
      "type": "BEAM",
      "class": "B",
      "arcs": [
        "P",
        "A"
      ]
    },
    {
      "type": "BEAM",
      "class": "B",
      "arcs": [
        "S",
        "A"
      ]
    }
  ],
  "fighters": {
    "capacity": 18
  }
}
